"""add fsgen_stack_lessons table

Revision ID: 3750c2e4e653
Revises: 46092fe54fa5
Create Date: 2026-07-20 17:27:46.728496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3750c2e4e653'
down_revision: Union[str, Sequence[str], None] = '46092fe54fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsgen_stack_lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stack', sa.Text(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('hits', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fsgen_stack_lessons_stack', 'fsgen_stack_lessons', ['stack'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fsgen_stack_lessons_stack', table_name='fsgen_stack_lessons')
    op.drop_table('fsgen_stack_lessons')
    # ### end Alembic commands ###
