"""initial fsgen tables

Revision ID: 46092fe54fa5
Revises: 
Create Date: 2026-07-15 11:24:48.183217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46092fe54fa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsgen_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('tech_stack', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('core_business_rule', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'generating'"), nullable=False),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('ix_fsgen_questions_question_id', 'fsgen_questions', ['question_id'], unique=True)
    op.create_table('fsgen_agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['fsgen_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fsgen_agent_logs_question_id', 'fsgen_agent_logs', ['question_id'], unique=False)
    op.create_table('fsgen_question_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('part', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['fsgen_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fsgen_question_files_question_id', 'fsgen_question_files', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fsgen_question_files_question_id', table_name='fsgen_question_files')
    op.drop_table('fsgen_question_files')
    op.drop_index('ix_fsgen_agent_logs_question_id', table_name='fsgen_agent_logs')
    op.drop_table('fsgen_agent_logs')
    op.drop_index('ix_fsgen_questions_question_id', table_name='fsgen_questions')
    op.drop_table('fsgen_questions')
    # ### end Alembic commands ###
